
theme = "hugo-theme-codex" 
title = "BasedLearning"
baseURL = "/"
copyright = "© 2022"

# Add your Disqus shortname here.
# disqusShortname = "" 

# Optional params
[params]
  # Follow the Hugo date/time format reference here: 
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Jan 2 2006"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  github = "https://github.com/sola1re"
  email = "mailto:iampaulmandon@gmail.com"

  
  # "Twitter", "GitHub", "Email", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconOrder = ["GitHub", "Email"]


  # Set to true to display page title in table of contents in blog posts.
  showPageTitleInTOC = true

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

###############CONTENT###############
[[menu.main]]
  identifier = "Home"
  name = " Home"
  title = "Home"
  url = "/"

[[menu.main]]
    identifier = "About"
    name = "About"
    title = "About"
    url = "/About"

[[menu.main]]
  identifier = "Calculus"
  name = "Calculus"
  title = "Calculus"
  url = "/calculus"

[[menu.main]]
    identifier = "Algebra"
    name = "Algebra"
    title = "Algebra"
    url = "/Algebra"

[[menu.main]]
    identifier = "Cheatsheets"
    name = "Cheatsheets"
    title = "Cheatsheets"
    url = "/Cheatsheets"

[[menu.main]]
    identifier = "Cryptography"
    name = "Cryptography"
    title = "Cryptography"
    url = "/Cryptography"

[[menu.main]]
    identifier = "Logic Theory"
    name = "Logic Theory"
    title = "Logic Theory"
    url = "/logic theory"

[[menu.main]]
    identifier = "Topology"
    name = "Topology"
    title = "Topology"
    url = "/Topology"

  